# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_remove_job_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=700)),
                ('description', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_by', to='belt_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='belt_app.User'),
            preserve_default=False,
        ),
    ]
