# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_auto_20180725_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='belt_app.Job'),
            preserve_default=False,
        ),
    ]
