# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0005_myjob_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjob',
            name='job',
        ),
    ]
